### PR TITLE
Adding new logos for Labs and Toolkit

### PR DESCRIPTION
**Pull request by niels9001**
Moving old logo's to 'Legacy' folder, and adding icons for Labs and Toolkit. Few .png sizes and .svg

### CODE REVIEW

**Comment by Nirmal4G** [comment]
We don't need to back-up the old logos, that's what the Git is for. Just tag the last commit before this and delete those files in this commit/PR.

**Comment by Nirmal4G** [comment]
It seems other variants are missing, for .NET and Maui?

**Comment by niels9001** [comment]
Added .NET and nuget variants for all toolkits

**Review by michael-hawker — APPROVED** [review]
Looks amazing! 🎉 FYI @kphillpotts I know MAUI mostly aligns with the .NET brand guidelines, but if there was any discussions around giving it more identity let us know. If anything, we can also generate the toolbox with a different shade of colors or some other symbol if you'd like so we can update the MAUI toolboxes to the modern design and have consistency across the Toolkit organization.

**Pull request merged**
